apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: nginx
    env: stg
spec:
  # stg: replicas 3->1
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-app-container
        image: gcr.io/sample-cicd-271901/test-go-image:latest
        ports:
        - containerPort: 8888