apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stg-
commonLabels:
  app: test

patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../../base
images:
- name: gcr.io/sample-cicd-271901/test-go-image
  newTag: 88a089773e6db243c57599e30f8dd27af6f4f18f
