apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stg-
commonLabels:
  app: test

patchesStrategicMerge:
- deployment_patch.yaml
images:
- name: gcr.io/sample-cicd-271901/test-go-image
  newTag: b082175caf57e247d37268f9b826068384e64986
resources:
- ../../base
