apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stg-
commonLabels:
  app: test

resources:
- namespace.yaml
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../../base
images:
- name: gcr.io/sample-cicd-271901/test-go-image
  newTag: ad948427c121c88d29854ae4f47e3fde56b8ff17
