apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stg-
commonLabels:
  app: test

patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../../base
images:
- name: gcr.io/sample-cicd-271901/test-go-image
  newTag: e0a063bc9a021f7762aee159fc32ddb8efb9904d
