version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  deploy_to_staging_cluster:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: apt-get update for wget
          command: |
            apt-get update
            apt-get install -y wget
      - run:
          name: install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            mv kubectl /usr/local/bin
            chmod +x /usr/local/bin/kubectl
      - run:
          name: install kustomize
          command: |
            wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
            tar xvzf kustomize_v3.5.4_linux_amd64.tar.gz
            mv kustomize /usr/local/bin
            chmod +x /usr/local/bin/kustomize
      - run:
          name: set up google cloud sdk
          command: |
            if [ "${CIRCLE_BRANCH}" == "stg" ]; then
              apt-get install -qq -y gettext
              echo ${ACCT_AUTH} | base64 -d > ${HOME}/account-auth.json
              gcloud auth activate-service-account --key-file=${HOME}/account-auth.json
              gcloud --quiet config set project ${GCP_PROJECT}
              gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
              gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}    
            fi
      - run:
          name: deploy manifests to gke cluster
          command: |
            echo ./overlays/production
            kustomize build ./overlays/staging | kubectl apply -n prd -f -
      - slack/status:
          include_project_field: true
          success_message: 'Branch: $CIRCLE_BRANCH\nUser：$CIRCLE_USERNAME'
          failure_message: 'Branch: $CIRCLE_BRANCH\nUser：$CIRCLE_USERNAME'
          webhook: ${SLACK_WEBHOOK}
  deploy_to_prodction_cluster:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: apt-get update for wget
          command: |
            apt-get update
            apt-get install -y wget
      - run:
          name: install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            mv kubectl /usr/local/bin
            chmod +x /usr/local/bin/kubectl
      - run:
          name: install kustomize
          command: |
            wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
            tar xvzf kustomize_v3.5.4_linux_amd64.tar.gz
            mv kustomize /usr/local/bin
            chmod +x /usr/local/bin/kustomize
      - run:
          name: set up google cloud sdk
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apt-get install -qq -y gettext
              echo ${ACCT_AUTH} | base64 -d > ${HOME}/account-auth.json
              gcloud auth activate-service-account --key-file=${HOME}/account-auth.json
              gcloud --quiet config set project ${GCP_PROJECT}
              gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
              gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}    
            fi
      - run:
          name: deploy manifests to gke cluster
          command: |
            echo ./overlays/production
            kustomize build ./overlays/production | kubectl apply -n prd -f -
      - slack/status:
          include_project_field: true
          success_message: 'Branch: $CIRCLE_BRANCH\nUser：$CIRCLE_USERNAME'
          failure_message: 'Branch: $CIRCLE_BRANCH\nUser：$CIRCLE_USERNAME'
          webhook: ${SLACK_WEBHOOK}
workflows:
  version: 2
  build:
    jobs:
      - deploy_to_prodction_cluster:
          filters:
            branches:
              only: master
      - deploy_to_staging_cluster:
          filters:
            branches:
              only: stg