version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  deploy_to_cluster:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: set up google cloud sdk
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apt-get install -qq -y gettext
              echo ${GCP_SERVICE_ACCOUNT_KEY} | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${GCP_PROJECT}
              gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
              gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME       
            fi
      - run:
          name: deploy manifests to gke cluster
          command: |
            kustomize build ~/${HOME} | kubectl apply -f -
            kubectl rollout status deployment ${DEPLOYMENT_NAME}
      - slack/status:
          include_project_field: true
          success_message: 'Branch: $CIRCLE_BRANCH\nUser：$CIRCLE_USERNAME'
          failure_message: 'Branch: $CIRCLE_BRANCH\nUser：$CIRCLE_USERNAME'
          webhook: ${SLACK_WEBHOOK}
workflows:
  version: 2
  build:
    jobs:
      - deploy_to_cluster:
          filters:
            branches:
              only: master