apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test
    env: prd
spec:
  # prd: replicas 3
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-app-container
        ports:
        - containerPort: 8888
        # prd: set resource limits and requests
        resources:
          limits:
            memory: "200Mi"
            cpu: "1"
          requests:
            memory: "100Mi"